### ISSUE TITLE
Invoice Transaction Tables Have Red (Credit) and Green (Debit) Highlighting

### ISSUE THREAD

**Issue by GEvanscsumb** [North-Vine-Engineering/ibs-server#38]
## Description / User Story 
As a user, I would like to easily identify which transaction is a credit or debit by having its row in the table highlighted in red and green respectively. For credits, I would also expect the amount to be in parenthesis to indicate a negative value.

## Tasks

- [ ] Add table row highlighting based on transaction type.
- [ ] Add parenthesis to credit transactions
- [ ] Remove Type from data column
